### ISSUE TITLE
Please Update README File

### ISSUE THREAD

**Issue by Gabriel-Assuncao** [cran/COVIDIBGE#1]
In previous versions of the COVIDIBGE package, the README file was accidentally replaced by the file referring to the PNSIBGE package, however such inconsistency has already been fixed in the current versions of the COVIDIBGE package.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly in the `DESCRIPTION` file. Thanks!
